config { 
  type: "table" 
}
SELECT 
    AVG(temp) as mean_temp,
    SUBSTR(year,1,3) || "0s" AS decade,
    country
  FROM `bigquery-public-data.noaa_gsod.gsod*` AS gsod
  JOIN `bigquery-public-data.noaa_gsod.stations` AS stations
    ON gsod.stn = stations.usaf AND gsod.wban = stations.wban
  WHERE country IN ("US","UK","CN") and cast(year as INT64) between 1930 and 2020 
  GROUP BY decade, country
  ORDER BY decade, country